version: '3.8'

services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.4
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: quay.io/debezium/kafka:2.4
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  postgres:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxca
      POSTGRES_DB: ingestion-service-db
    command: ["postgres", "-c", "wal_level=logical"]

  connect:
    image: quay.io/debezium/connect:2.4
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    depends_on:
      - kafka
      - postgres

  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    ports:
      - 8090:8080
    depends_on:
      - kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            debezium-kafka:
              properties:
                bootstrap.servers: "kafka:29092"

  debezium-init:
      image: curlimages/curl:latest
      depends_on: [connect]
      volumes:
        - ./connector-config.json:/connector-config.json
      command: >
        /bin/sh -c "
        echo 'Waiting for Debezium Connect to start...';
        while ! curl -s http://connect:8083/ > /dev/null; do sleep 5; done;
        echo 'Debezium is up! Registering connector...';
        curl -X POST -H 'Content-Type: application/json' --data @/connector-config.json http://connect:8083/connectors/;
        echo 'Connector registered.';
        "
